### ISSUE TITLE
Missing C:\Python\Lib\site-packages\tensorsignatures\data

### ISSUE THREAD

**Issue by animesh** [sagar87/tensorsignatures#1]
* tensorsignatures version: 2.0
* Python version: 3.7
* Operating System: Windows 10

### Description
Running example from https://tensorsignatures.readthedocs.io/en/latest/tutorials.html#getting-started 
```
import tensorsignatures as ts
data_set = ts.TensorSignatureData(seed=573, rank=3, samples=100, dimensions=[3, 5], mutations=1000)
```
throws error of missing sim_sig.txt and other.txt.

Creating C:\Python\Lib\site-packages\tensorsignatures\data and downloading sim_sig.txt and other.txt into it from github repo   seems to fix it?

**Comment by sagar87** [comment]
Hi animesh! Interesting, I assume you installed the package using pip? To be honest, I didn't try to run the package on Windows yet; but I didn't see that error on MacOs or Linux. Will look into it. Also, note that the documentation at this point is not complete yet, I am planning to release a few updates during the next days.

**Comment by animesh** [comment]
Awesome! Very interesting work i must say and Yes i used pip :)

**Comment by sagar87** [comment]
Thank you very much, I'll be in touch about this issue asap.

**Comment by sagar87** [comment]
The current version should fix the issue `pip install tensorsignatures==0.4.0`
