### ISSUE TITLE
Annotations for nucleasome and clustering issues

### ISSUE THREAD

**Issue by emauryg** [sagar87/tensorsignatures#12]
* tensorsignatures version: latest as of 12/18/2020
* Python version: N/A
* Operating System: Linux (HPC)

### Description

Trying to annotate melanoma dataset from the PCAWG MAF files. 

### What I Did

Tried to annotate for the different categories using the R scripts and reference sets provided in Mutations.R and Constants.Rdata respectively. However, looking at the nucleosome annotation function I noticed that it only annotates 0 or 1, not the 4 states specified in the preprint. Similarly, looking at the mutation clustering annotation, it seems that the transition probabilities are different from those specified in the paper. 
```

getNucleosomeData <- function(){
    nucleosomes <- read.table(nucleosomePath)
    NucRanges = GRanges(seqnames=nucleosomes$V1,
        ranges=IRanges(start=nucleosomes$V2, end=nucleosomes$V3),
        strand="+")
    NucRanges <- reduce(NucRanges)
    NucRanges <- NucRanges[!width(NucRanges)>2] # get rid of strange points
    NucleosomeCovered <- NucRanges+73
    NucleosomeCovered <- reduce(NucleosomeCovered) # genomic regions within nucleosomes
    NucleosomeCovered <- toNCBI(NucleosomeCovered)
    GRCh37 <- getStandardChromosomes()
    NotNucleosomeCovered <- setdiff(GRCh37, NucleosomeCovered, ignore.strand=T)
    NucleosomePartition <- sort(c(NotNucleosomeCovered, NucleosomeCovered), ignore.strand=T)
    mcols(NucleosomePartition)$state <- 0
    mcols(NucleosomePartition[strand(NucleosomePartition) == "+"])$state <- 1

    return(NucleosomePartition)
}

```
kataegis <- function(vcf, p=1e-3, q=0.1, r=100) {
    d <-  diff(start(vcf))
    w <- d > 1 & diff(as.numeric(seqnames(vcf))) == 0
    #p <- 1e-3 # P N>Kat
    #q <- 0.05 # P Kat>N
    P <- matrix(c(1-p,p,q, 1-q), ncol=2, byrow=TRUE) # Transition matrix
    p0 <- c(1,0)
    s <- c(mean(d[w]), r)
    dw <- d[w]
    l <- length(dw)
    T1 <- T2 <- matrix(0,ncol=l, nrow=2)
    T1[,1] <- log(c(q/(q+p), p/(q+p)))
    lP <- log(P)
    dg <- rbind(dgeom(dw, prob=1/s[1], log=TRUE), dgeom(dw, prob=1/s[2], log=TRUE))
    for(i in 2:l){
        x <- ((T1[,i-1] + lP) + dg[,i])
        T2[1,i] <- (x[1,1] < x[2,1])+1
        T2[2,i] <- (x[1,2] < x[2,2])+1
        T1[1,i] <- x[T2[1,i],1]
        T1[2,i] <- x[T2[2,i],2]
    }
    z <- numeric(l)
    z[l] <- 1
    for(i in l:2){
        z[i-1] <- T2[z[i],i]
    }
    k <- numeric(nrow(vcf))
    k[-1][w][-1] <- z[-l]-1
    k[-nrow(vcf)][w][-1] <- (z[-l]-1) | k[-nrow(vcf)][w][-1]
    #k[-1][w] <- z-1
    #k[-nrow(vcf)][w] <- (k[-nrow(vcf)][w]) | (z-1)
    kf <- factor(k, levels=0:1)
    return(kf)
}
```

```

**Comment by sagar87** [comment]
Hi emauryg, 

thanks for your interest in tensorsignatures. You can find the nucleosome state annotations in the `NUC` object of the `constants.Rdata` object:

```
> load("project/constants.rdata")
> NUC
GRanges object with 86116192 ranges and 1 metadata column:
             seqnames              ranges strand |     state
                <Rle>           <IRanges>  <Rle> | <numeric>
         [1]        1                1-58      * |         0
         [2]        1           59-834155      * |         0
         [3]        1       834156-834213      * |         3
         [4]        1       834214-834218      * |         2
         [5]        1       834219-834223      * |         1
         ...      ...                 ...    ... .       ...
  [86116188]        X 154929674-155270502      * |         0
  [86116189]        X 155270503-155270560      * |         0
  [86116190]        Y                1-58      * |         0
  [86116191]        Y         59-59373508      * |         0
  [86116192]        Y   59373509-59373566      * |         0
  -------
  seqinfo: 24 sequences from an unspecified genome
```

The state column of the `NUC` object represents nucleosome states (`0` baseline: i.e. not on a nucleosome, `1` minor out, `2` minor in, `3` linker region). You can use these annotations to classify the variants of your MAF files (this should be somewhat similar to `getNucleosomeState` of `mutations.R`).

Thanks for pointing out incoherence of reported transition probabilities in the `kataegis` function, I'll double check if there is a typo.

Best wishes,
Harald.

**Comment by emauryg** [comment]
I see. Do you have a particular tissue from PCAWG for which you found mutations with a nucleosomal genomic context that is not 0? When I tried to annotate all the PCAWG from their MAFs it seems the intervals provided by NUC are all annotated by state 0. 

Has there been any update regarding the kataegis function? 

Thank you for the comments!

**Comment by sagar87** [comment]
Certainly most of the tissues should have SNVs on various nucleosome states. Perhaps double check your annotation function ? It should somewhat follow the lines of

```
getNucleosomeState <- function(vcf, consensusState) {
    h <- findOverlaps(vcf, consensusState, ignore.strand=T) # ignore.strand is important
    stopifnot(length(h) == length(granges(vcf))) # sanityCheck
    factor(mcols(consensusState[subjectHits(h)])$state, levels=c(0,1,2,3))
}
```

Running the `kataegis` function with default settings should give you the same results as we report in our preprint.

Hope this helps, best wishes.

**Comment by emauryg** [comment]
I used the same function from getNucleosomeState() to try to annotate the SNVs, and still got all 0 annotation. The same does not happen when I annotate the epigenomic states etc, so there shouldn't be anything wrong with the GRanges object.

**Comment by sagar87** [comment]
Hm interesting, if you do not mind to share an example MAF file and the script you used to annotate it I could have a look at it (harald at ebi.ac.uk).
